name: Welcome First-Time Contributors

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: >
            Hi @${{ github.actor }}, thank you for opening your first issue in this repository! We value your contribution. Our team will review your issue and get back to you as soon as possible. In the meantime, please make sure to provide all necessary details and follow the issue template.

          pr-message: >
            Hi @${{ github.actor }}, thank you for submitting your first pull request! We appreciate your effort to improve our project. Our team will review your PR shortly. Please ensure that your PR adheres to the contribution guidelines and that all necessary tests are included. If you have any questions or need further assistance, feel free to reach out.
